kind: pipeline
name: default

steps:
  - name: test
    image: openjdk
    commands:
      - ./gradlew test
    when:
      branch:
        - master
      event:
        - push
        - pull_request

